### PR TITLE
Allocgate 2.0 slain

### PR DESCRIPTION
**Pull request by SuperAuguste**

### CODE REVIEW

**Comment by SuperAuguste** [comment]
@alexnask Tuple support broke semantic token highlighting and enums it seems. Any ideas?

**Comment by alexnask** [comment]
@SuperAuguste

Semantic token highlighting is working just fine for me (I'm 100% confident since I don't use any zig extention other than zls on VSCode  specifically to test it) although I am running a handful of commits behind master  
Not sure what could have caused the enum compleitons to break though.

**Comment by SuperAuguste** [comment]
Yeah everything works for me too, I just mean that they fail in the test suite for some reason :(

**Comment by nektro** [comment]
`build.zig` should be updated too

**Comment by SuperAuguste** [comment]
Good call - I'll bump it up next time I commit.

**Pull request merged**
