### PR TITLE
Fix building for Zig version 0.11.0-dev.4332+43b830415

### PR DESCRIPTION
**Pull request by BratishkaErik**

### CODE REVIEW

**Comment by kamidev** [comment]
@BratishkaErik, this fix works, but requires zig 0.11.0-dev.4333+33e4cbb20. 

@kubkon found and fixed a typo in the original breaking change: https://github.com/ziglang/zig/commit/33e4cbb20f7cac71e5feaeeeb4c7576ab4708697

**Comment by kubkon** [comment]
> @BratishkaErik, this fix works but requires zig 0.11.0-dev.4333+33e4cbb20.
> 
> @kubkon found and fixed a typo in the original breaking change: [ziglang/zig@33e4cbb](https://github.com/ziglang/zig/commit/33e4cbb20f7cac71e5feaeeeb4c7576ab4708697)

Correction: a contributor @GethDW found it first - I just clicked the merge button ;-) So kudos to them for a quick patch!

**Comment by BratishkaErik** [comment]
Hm? I can build zls just fine without this fix...

**Comment by kamidev** [comment]
> Hm? I can build zls just fine without this fix...

I am building zls on macOS 13.5 using an M2 mac. Have been building zig, zls and a few other projects for a while. When the LazyPath commits merged some projects, including zls, broke. I tried to fix zls like you do here, but it didn't work until this typo was fixed on zig master.

**Comment by BratishkaErik** [comment]
> > Hm? I can build zls just fine without this fix...
> 
> I am building zls on macOS 13.5 using an M2 mac. Have been building zig, zls and a few other projects for a while. When the LazyPath commits merged some projects, including zls, broke. I tried to fix zls like you do here, but it didn't work until this typo was fixed on zig master. Did it work locally for you?

Yep, and there are no references to `addCopyFile` in zls's build.zig or in stdlib code (except deprecation notice for `getFileSource`)

**Comment by kamidev** [comment]
> > > Hm? I can build zls just fine without this fix...
> > 
> > 
> > I am building zls on macOS 13.5 using an M2 mac. Have been building zig, zls and a few other projects for a while. When the LazyPath commits merged some projects, including zls, broke. I tried to fix zls like you do here, but it didn't work until this typo was fixed on zig master. Did it work locally for you?
> 
> Yep, and there are no references to `addCopyFile` in zls's build.zig or in stdlib code (except deprecation notice for `getFileSource`)

Thanks! I just rolled back my zig and checked again. The fix does work indeed work for the specified zig version. Maybe a cache mistake on my end, sorry about that.

**Review by Techatrix — APPROVED** [review]

**Pull request merged**
