### PR TITLE
node tag `.identifier` != token tag `.identifier`, eg `@Some`

### LINKED ISSUE #1645: zls crashes
### Zig Version

0.12.0-dev.1746+19af8aac8

### Zig Language Server Version

6b05cb645abf1118ea338b7f356da41b63338774

### Steps to Reproduce and Observed behavior

Create a new .zig file and paste the following code into it:
```zig
const std = @import("std");

const main = @import("root");
const blocks = main.blocks;
const chunk = main.chunk;

const Channel = enum {
    red,
    green,
    blue,

    pub fn shift(self: Channel) u5 {
        switch (self) {
            .red => return 16,
            .green => return 8,
            .blue => return 0,
        }
    }
};

pub const ChannelChunk = struct {
    data: [chunk.chunkVolume]u8,
    mutex: std.Thread.Mutex,
    ch: *chunk.Chunk,
    channel: Channel,

    pub fn init(self: *ChannelChunk, ch: *chunk.Chunk, channel: Channel) !void {
        self.mutex = .{};
        self.ch = ch;
        self.channel = channel;
        @memset(&self.data, 0);
    }

    pub fn propagateLights(self: *ChannelChunk, lights: [][3]u8) void {
        const Entry = struct {
            x: i8,
            y: i8,
            z: i8,
            value: u8,

            fn compare(_: void, a: @This(), b: @This) std.math.Order {
                if (a.value > b.value) return .gt;
                if (a.value < b.value) return .lt;
                return .eq;
            }
        };
        var lightQueue = std.PriorityQueue(Entry, void, Entry.compare).init(main.globalAllocator, {});
        for (lights) |pos| {
            const index = chunk.getIndex(pos[0], pos[1], pos[2]);
            try lightQueue.add(.{ .x = @intCast(pos[0]), .y = @intCast(pos[1]), .z = @intCast(pos[2]), .value = @intCast(self.ch.blocks[index].light() >> self.channel.shift() & 255) });
        }

        while (lightQueue.removeOrNull()) |entry| {}
    }
};

```
Observe that zls crashes with the following stack trace:
```
thread 15135 panic: reached unreachable code
/home/mint/Cubyz/compiler/zig/lib/std/debug.zig:342:14: 0x368f62 in assert (zls)
    if (!ok) unreachable; // assertion failure
             ^
/home/mint/zls/src/offsets.zig:181:21: 0x5843aa in identifierTokenToNameLoc (zls)
    std.debug.assert(tree.tokens.items(.tag)[identifier_token] == .identifier);
                    ^
/home/mint/zls/src/offsets.zig:186:60: 0x5103bb in identifierTokenToNameSlice (zls)
    return locToSlice(tree.source, identifierTokenToNameLoc(tree, identifier_token));
                                                           ^
/home/mint/zls/src/analysis.zig:3018:79: 0x4b8638 in resolveType (zls)
                    const param_type_name = offsets.identifierTokenToNameSlice(tree, main_tokens[param.type_expr]);
                                                                              ^
/home/mint/zls/src/features/semantic_tokens.zig:1008:34: 0x55b6be in writeIdentifier (zls)
        if (try child.resolveType(builder.analyser)) |decl_type| {
                                 ^
debug: (server): Took 0ms to process request-4-textDocument/foldingRange on Thread 15132
/home/mint/zls/src/features/semantic_tokens.zig:845:32: 0x4f1853 in writeNodeTokens (zls)
            try writeIdentifier(builder, main_token);
                               ^
/home/mint/zls/src/features/semantic_tokens.zig:851:32: 0x4f192d in writeNodeTokens (zls)
            try writeNodeTokens(builder, data.lhs);
                               ^
/home/mint/zls/src/features/semantic_tokens.zig:822:32: 0x4f940d in writeNodeTokens (zls)
            try writeNodeTokens(builder, node_data[node].rhs);
                               ^
/home/mint/zls/src/features/semantic_tokens.zig:550:32: 0x4f67f9 in writeNodeTokens (zls)
            try writeNodeTokens(builder, if_node.ast.cond_expr);
                               ^
/home/mint/zls/src/features/semantic_tokens.zig:306:36: 0x4f276d in writeNodeTokens (zls)
                try writeNodeTokens(builder, child);
                                   ^
/home/mint/zls/src/features/semantic_tokens.zig:454:36: 0x4f49e8 in writeNodeTokens (zls)
                try writeNodeTokens(builder, node_data[node].rhs);
                                   ^
/home/mint/zls/src/features/semantic_tokens.zig:377:40: 0x4f393d in writeNodeTokens (zls)
                    try writeNodeTokens(builder, child);
                                       ^
/home/mint/zls/src/features/semantic_tokens.zig:338:32: 0x4f30f4 in writeNodeTokens (zls)
            try writeNodeTokens(builder, var_decl.ast.init_node);
                               ^
/home/mint/zls/src/features/semantic_tokens.zig:306:36: 0x4f276d in writeNodeTokens (zls)
                try writeNodeTokens(builder, child);
                                   ^
debug: (server): Took 0ms to process request-5-textDocument/hover on Thread 15133
/home/mint/zls/src/features/semantic_tokens.zig:454:36: 0x4f49e8 in writeNodeTokens (zls)
                try writeNodeTokens(builder, node_data[node].rhs);
                                   ^
/home/mint/zls/src/features/semantic_tokens.zig:377:40: 0x4f393d in writeNodeTokens (zls)
                    try writeNodeTokens(builder, child);
                                       ^
/home/mint/zls/src/features/semantic_tokens.zig:338:32: 0x4f30f4 in writeNodeTokens (zls)
            try writeNodeTokens(builder, var_decl.ast.init_node);
                               ^
/home/mint/zls/src/features/semantic_tokens.zig:1041:28: 0x4b06ae in writeSemanticTokens (zls)
        try writeNodeTokens(&builder, child);
                           ^
/home/mint/zls/src/Server.zig:1237:51: 0x476947 in semanticTokensFullHandler (zls)
    return try semantic_tokens.writeSemanticTokens(
                                                  ^
/home/mint/zls/src/Server.zig:2017:85: 0x449186 in sendRequestSync__anon_19821 (zls)
        .@"textDocument/semanticTokens/full" => try server.semanticTokensFullHandler(arena, params),
                                                                                    ^
debug: (server): Took 0ms to process request-6-textDocument/codeAction on Thread 15134
/home/mint/zls/src/Server.zig:2096:58: 0x4086b8 in processMessage (zls)
                const result = try server.sendRequestSync(arena_allocator.allocator(), @tagName(method), params);
                                                         ^
/home/mint/zls/src/Server.zig:2113:33: 0x3abdc5 in processMessageReportError (zls)
    return server.processMessage(message) catch |err| {
                                ^
/home/mint/zls/src/Server.zig:2151:62: 0x381af1 in processJob (zls)
            const response = server.processMessageReportError(parsed_message.value) orelse return;
                                                             ^
/home/mint/Cubyz/compiler/zig/lib/std/Thread/Pool.zig:94:39: 0x380cde in runFn (zls)
            @call(.auto, func, closure.arguments);
                                      ^
/home/mint/Cubyz/compiler/zig/lib/std/Thread/Pool.zig:133:18: 0x4385f4 in worker (zls)
            runFn(&run_node.data);
                 ^
/home/mint/Cubyz/compiler/zig/lib/std/Thread.zig:412:13: 0x3f3d5d in callFn__anon_17891 (zls)
            return default_value;
            ^
/home/mint/Cubyz/compiler/zig/lib/std/Thread.zig:1210:30: 0x392593 in entryFn (zls)
            }
                             ^
/home/mint/Cubyz/compiler/zig/lib/c.zig:239:13: 0x90f410 in clone (c)
            asm volatile (
            ^
???:?:?: 0x0 in ??? (???)
```

### Expected Behavior

zls shouldn't crash

### PR DESCRIPTION
**Pull request by nullptrdevs**
fixes #1645

### CODE REVIEW

**Comment by SuperAuguste** [comment]
This is @Techatrix's worse enemy :P

**Comment by nullptrdevs** [comment]
I've felt like reworking `identifierTokenToNameSlice` and related to do the check(s) and return an error/null every time it has happened and I just might, because it also affects `const Self = @This;`.

> Could you add a new test case?

What would it look like?

**Comment by Techatrix** [comment]
> I've felt like reworking `identifierTokenToNameSlice` and related to do the check(s) and return an error/null every time it has happened and I just might, because it also affects `const Self = @This;`.

How about making `identifierTokenToNameSlice` support `zig.tokenizer.Token.Tag.builtin` and make it return `@This` when called on a `@This` token.

> What would it look like?

Convert the code in #1645 into a semantic token test and reduce its size while ensuring that its still hits the assertion.

**Comment by Techatrix** [comment]
`identifierTokenToNameSlice` and all other variants

**Comment by nullptrdevs** [comment]
> `identifierTokenToNameSlice` and all other variants

I think it's better to be aware that they might fail + code(checks) dedup.

**Comment by nullptrdevs** [comment]
I went with errors, returning `null` felt vague and forced.

**Pull request closed without merging**
