### PR TITLE
new build on save with watch mode

### LINKED ISSUE #2001: Provide a configuration option to use incremental compilation for build-on-save
After ziglang/zig#21063 is merged, the Zig compiler is able to perform certain incremental updates correctly. There's still a ways to go before it's generally usable, but `-fno-emit-bin` builds will be the first thing to work correctly, and some do under that PR. For instance, simple incremental updates to the compiler itself typically do the right thing now.

In the future, incremental compilation will be able to help the Zig compiler expose detailed semantic information to ZLS or a similar project (ziglang/zig#615). However, ZLS can still make good use of incremental compilation before upstream progress is made there.

If ZLS' build runner introduces support for `std.Build.Watch` like the standard build runner does, which should be a relatively straightforward enhancement, it can begin using incremental compilation for build-on-save. (Incremental compilation currently only works if the compiler process stays running via the compiler server protocol: serialization and deserialization of compiler state to disk is a WIP feature.)

This functionality should be behind a config option which can be disabled by default. It's definitely possible to crash the compiler right now, or even to get false positive compile errors; incremental compilation is not stable, even when not emitting a binary. When we *are* emitting a binary, it'll basically crash immediately, so this will currently only work if the user is providing via `build_on_save_step` the name of a step which will pass `-fno-emit-bin` to the compiler. Nevertheless, it might be valuable to expose this as an option for people to try out.

### LINKED ISSUE #2095: Diagnostics relatedInformation contain invalid URLs
### Zig Version

latest

### ZLS Version

latest

### Client / Code Editor / Extensions

kakoune

### Steps to Reproduce and Observed Behavior

Open a Zig file containing

```zig
pub fn main() void {}
pub fn main() void {}
```

zig-lsp sends diagnostics with `"uri":"/"` which seems invalid?

For more details, see the original report at https://github.com/kakoune-lsp/kakoune-lsp/issues/811

### Expected Behavior

`"uri"://file/path/to/file.zig"`

### Relevant log output

LSP: DEBG From server zls: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///tmp/afac/main.zig","diagnostics":[{"range":{"start":{"line":0,"character":7},"end":{"line":0,"character":11}},"severity":1,"code":"ast-check","source":"zls","message":"duplicate struct member name 'main'","relatedInformation":[{"location":{"uri":"/","range":{"start":{"line":1,"character":7},"end":{"line":1,"character":11}}},"message":"duplicate name here"},{"location":{"uri":"/","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":3}}},"message":"struct declared here"}]}]}}

### PR DESCRIPTION
**Pull request by Techatrix**
This PR replaces the current build on save implementation with a new one that is based on Zig's `zig build --watch` feature. This can be combined with the `build_on_save_args` config option to enable incremental compilation. fixes #2001

Here is a small showcase where I use the equivalent of `zig build check --watch -fincremental`:

<details>

[Showcase](https://github.com/user-attachments/assets/920d432e-6d4e-4f62-8163-345ebffadb32)

<summary>Show Video</summary>

I used the [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens) extension to display the error messages inline.

</details>

The minimum runtime Zig version has been bumped from `0.12.0` to `0.14.0-dev.310+9d38e82b5`. This means that the latest mach nominated zig version (`0.14.0-dev.1911+3bf89f55c`) is still supported.
The build on save diagnostics are no longer removed after editing the document. The source location of the error message is not being updated when the document gets modified but this can be implement in the future.

- fixes  #2095
- partially addresses #2060
- errors are stored as `std.zig.ErrorBundle` which unblocks #2018

I have only tested this on Linux and Windows with VS Code. Who know what kind of bugs are still lurking around :shrug:

### CODE REVIEW

**Comment by leecannon** [comment]
I've tried this with a few of my projects and it works well :zap:

**Comment by lishaduck** [comment]
@Techatrix, is there a way to turn this off? I skimmed the diff and I didn't see one.
This breaks build_on_save in VS Code on macOS (#2221/https://github.com/ziglang/zig/issues/21905)

**Comment by kristoff-it** [comment]
On macOS there are two bugs related to this feature, one is the one linked above, the second is that --watch crashes on macOS ([fixed here](https://github.com/ziglang/zig/pull/23247), should become available in 0.14.1)

**Comment by Techatrix** [comment]
> @Techatrix, is there a way to turn this off? I skimmed the diff and I didn't see one.

No, this PR has **replaced** the previous build on save implementation. Excluding bugs like these, there should be no reason to need the old implementation.

If no progress is being made on https://github.com/ziglang/zig/issues/21905, I will look into patching ZLS.

**Pull request merged**
