### PR TITLE
DocumentScope: labeled blocks musings

### PR DESCRIPTION
**Pull request by llogick**
See https://github.com/zigtools/zls/issues/1726

### CODE REVIEW

**Review by travisstaloch — COMMENTED** [review]
I took this PR for a quick test drive and verified that it does fix the goto definition label/variable confusion described in #1726.  In that regard I can approve these changes :+1:.

However, I'm not familiar enough with the codebase to say that I think they're correct.  So I'll defer to someone else.  Perhaps @SuperAuguste , @Techatrix or @leecannon could weigh in here?

**Comment by travisstaloch** [comment]
I'll keep using this branch for a few days and report if I notice any issues here.

**Comment by travisstaloch** [comment]
One thing that I would like to see is either a goto definition test or a rename test.  I've never made one myself.  But I think [here](https://github.com/zigtools/zls/blob/master/tests/lsp_features/definition.zig#L171) is where the goto def tests live.

**Comment by travisstaloch** [comment]
Here are some passing tests I would like to see included:
```diff
diff --git a/tests/lsp_features/definition.zig b/tests/lsp_features/definition.zig
index 769c049..1926e6c 100644
--- a/tests/lsp_features/definition.zig
+++ b/tests/lsp_features/definition.zig
@@ -168,6 +168,28 @@ test "multiline builder pattern" {
     );
 }
 
+test "block and decl with same name 1" {
+    try testDefinition(
+        \\test {
+        \\    _ = <def><decl>blk</decl></def>: {
+        \\        const blk = 1;
+        \\        break :<>blk blk;
+        \\    };
+        \\}
+    );
+}
+
+test "block and decl with same name 2" {
+    try testDefinition(
+        \\test {
+        \\    _ = blk: {
+        \\        const <def><decl>blk</decl></def> = 1;
+        \\        break :blk <>blk;
+        \\    };
+        \\}
+    );
+}
+
 /// - use `<>` to indicate the cursor position
 /// - use `<decl>content</decl>` to set the expected range of the declaration
 /// - use `<def>content</def>` to set the expected range of the definition
```

**Review by travisstaloch — COMMENTED** [review]
New tests look good :+1:

**Review by Techatrix — CHANGES_REQUESTED** [review]

**Comment by Techatrix** [comment]
This is going to conflict with #1754.

**Comment by travisstaloch** [comment]
Update: I've been using this branch for a couple weeks now and haven't noticed any issues.

**Review by Techatrix — APPROVED** [review]

**Pull request merged**
