### PR TITLE
Update to 0.11.0-dev.3737+9eb008717

### LINKED ISSUE #1248: Fixing compatibility with latest Zig versions
Zls is currently not compilable on the latest commits of Zig (`0.11.0-dev.3735+a72d634b7` as of writing) due to 2 breaking changes:

## 1. JSON API rewrite

The JSON api of Zig was refactored in a recent commit: https://github.com/ziglang/zig/commit/32cb9462ffa0a9df7a080d67eaf3a5762173f742

Main changes:
- `std.json.parseFrom...(T: type...)` now return `std.json.Parsed(T)` instead of T
-  `json.parseFree(type, allocator, value)` was replaced by `std.json.Parsed.deinit(self: @This())`

This will require a somewhat extensive refactor of the way zls handles data loaded from json files.

Also affects the `tres` dependency

## 2. Casting operation renaming

All `@XtoY` casting operations were replaced with `@YFromX` in commit: https://github.com/ziglang/zig/commit/50339f595aa6ec96760b1cd9f8d0e0bfc3f167fc

Also affects the dependencies:
- tres https://github.com/ziglibs/tres
- diffz https://github.com/ziglibs/diffz
- binned_allocator https://gist.github.com/silversquirl/c1e4840048fdf48e669b6eac76d80634 it's a gist, so no good way to PR :(

This is a trivial fix, just have to run `zig fmt` on the dependencies, update them in zon, and then run `zig fmt` on zls too.

# Task list:

- [x] dependency upstream fixes
  - [x] diffz https://github.com/ziglibs/diffz/pull/14
  - [x] tres https://github.com/ziglibs/tres/pull/14
  - [ ] binned_allocator (Using a fork for now, upstream still hasn't merged the fix)
- [x] update zon to fixed dependencies
- [x] apply `zig fmt` to zls
- [ ] #1251
  - [x] Temporary `legacy_json.zig` compatibility layer

Working PR: https://github.com/zigtools/zls/pull/1249

### PR DESCRIPTION
**Pull request by FalsePattern**
Fixes #1248.

### Dependencies in Zon:
- diffz and tres have been fully updated upstream
- binned_allocator is a fork for now, upstream merges in gists are difficult. Marked this information in zon as a comment.

### JSON api:
A full fix has been deferred to a later time, and the memory behaviour of the old json api's `parseFree` and `parseFrom...` was copied into the `src/legacy_json.zig` file. This is to avoid delaying the update longer than absolutely necessary.

## Additional tested versions
 Since the creation of this PR, it was also tested on (linux-x86_64):
`0.11.0-dev.3771+128fd7dd0` binaries from the website
`0.11.0-dev.3781+c60896743` compiled from master
Both passed `zig build test` successfully.

### CODE REVIEW

**Comment by nullptrdevs** [comment]
Do `zig build gen -- --generate-version-data master`

**Comment by SuperAuguste** [comment]
@FalsePattern I think adding an arena alongside Config would make the most sense rather than keeping around parseFree; I'd be happy to implement this if you don't want to mess with the memory management stuff too much :)

**Comment by FalsePattern** [comment]
> @FalsePattern I think adding an arena alongside Config would make the most sense rather than keeping around parseFree; I'd be happy to implement this if you don't want to mess with the memory management stuff too much :)

Please do. I don't have too much experience with zig yet so i avoided doing any large-scale rewrites and focused on making a more or less direct update in this PR.

**Review by leecannon — APPROVED** [review]

**Comment by leecannon** [comment]
Looks good, will merge as is and open an issue (https://github.com/zigtools/zls/issues/1251) to track improving the json part.

**Pull request merged**
