### PR TITLE
Basic import support

### PR DESCRIPTION
**Pull request by alexnask**
🥳

### CODE REVIEW

**Comment by alexnask** [comment]
This works pretty well from the limited testing I did.  
Now it needs cleanup + some checks to decrement document refcoutns when we remove imports.

**Comment by alexnask** [comment]
Also, I need to add the new config option to the README and fix the doc comment.

**Comment by SuperAuguste** [comment]
Looks good! Getting a crash when attempting to complete ArrayList.

```log
reached unreachable code
C:\Users\augus\Documents\zig\zig\build-release\lib\zig\std\debug.zig:228:14: 0x7ff6fa6c1078 in std.debug.assert (zls.obj)
    if (!ok) unreachable; // assertion failure
             ^
C:\Users\augus\Documents\zig\zig\build-release\lib\zig\std\segmented_list.zig:126:19: 0x7ff6fa701aa8 in std.segmented_list.SegmentedList(std.zig.tokenizer.Token,64)::std.segmented_list.SegmentedList(std.zig.tokenizer.Token,64).at (zls.obj)
            assert(i < self.len);
                  ^
C:\Users\augus\Documents\zig\zig\build-release\lib\zig\std\zig\ast.zig:39:49: 0x7ff6fa7018e2 in std.zig.ast.Tree::std.zig.ast.Tree.tokenSlice (zls.obj)
        return self.tokenSlicePtr(self.tokens.at(token_index));
                                                ^
C:\Users\augus\Documents\Programming\zig_oss\zlsp\zls-alex\src\analysis.zig:163:52: 0x7ff6fa7136fd in analysis.getChild (zls.obj)
                if (std.mem.eql(u8, tree.tokenSlice(vari.name_token), name)) return child;
                                                   ^
C:\Users\augus\Documents\Programming\zig_oss\zlsp\zls-alex\src\analysis.zig:222:40: 0x7ff6fa713bf3 in analysis.resolveTypeOfNode (zls.obj)
                        return getChild(latest_tree, left, string);
                                       ^
C:\Users\augus\Documents\Programming\zig_oss\zlsp\zls-alex\src\analysis.zig:187:37: 0x7ff6fa713932 in analysis.resolveTypeOfNode (zls.obj)
            return resolveTypeOfNode(latest_tree, vari.type_node orelse vari.init_node.?, import_ctx) orelse null;
                                    ^
C:\Users\augus\Documents\Programming\zig_oss\zlsp\zls-alex\src\analysis.zig:281:46: 0x7ff6fa712679 in analysis.getFieldAccessTypeNode (zls.obj)
                        if (resolveTypeOfNode(latest_tree, child, import_ctx)) |child_type| {
                                             ^
C:\Users\augus\Documents\Programming\zig_oss\zlsp\zls-alex\src\main.zig:282:40: 0x7ff6fa6f3a47 in completeFieldAccess (zls.obj)
    if (analysis.getFieldAccessTypeNode(tree, &tokenizer, &import_ctx)) |node| {
                                       ^
C:\Users\augus\Documents\Programming\zig_oss\zlsp\zls-alex\src\main.zig:528:40: 0x7ff6fa6dbb55 in processJsonRpc (zls.obj)
                try completeFieldAccess(id, handle, pos, config);
                                       ^
C:\Users\augus\Documents\Programming\zig_oss\zlsp\zls-alex\src\main.zig:661:35: 0x7ff6fa6c5355 in main (zls.obj)
                try processJsonRpc(&json_parser, buffer.items[index .. index + content_len], config);
                                  ^
C:\Users\augus\Documents\zig\zig\build-release\lib\zig\std\start.zig:134:65: 0x7ff6fa6c1f6e in std.start.WinMainCRTStartup (zls.obj)
    std.os.windows.kernel32.ExitProcess(initEventLoopAndCallMain());
```

**Comment by alexnask** [comment]
Fixed in 95b6e6cd6a9c3ff409b44daed6b398ba42e324be @SuperAuguste

**Comment by alexnask** [comment]
Example screenshot of just about the most complex situation this can handle  

image

Where

```zig
document_store: DocumentStore = ...;
// And
const DocumentStore = @import("document_store.zig");
```

**Comment by alexnask** [comment]
Example session of a test doc with a `const std = @import("std");` import.  
I typed `std.zig.` then deleted it and finally deleted the import.  

```
Standard library base uri: file:///c%3A/dev/zig/build-release/lib/zig/std/std.zig
Opened document: file:///c%3A/dev/test2.zig
New sane text for document file:///c%3A/dev/test2.zig
Opened document: file:///c%3A/dev/zls/src/analysis.zig
New sane text for document file:///c%3A/dev/zls/src/analysis.zig
Opened document: file:///c%3A/dev/zls/src/document_store.zig
New sane text for document file:///c%3A/dev/zls/src/document_store.zig
New sane text for document file:///c%3A/dev/test2.zig
Import final URI: file:///c%3A/dev/zig/build-release/lib/zig/std/std.zig
Opened document: file:///c%3A/dev/zig/build-release/lib/zig/std/std.zig
New sane text for document file:///c%3A/dev/zig/build-release/lib/zig/std/std.zig
INVALID: Id.Comptime
INVALID: Id.TestDecl
Import final URI: file:///c%3A/dev/zig/build-release/lib/zig/std/std.zig
Import final URI: file:///c%3A/dev/zig/build-release/lib/zig/std/zig.zig
Opened document: file:///c%3A/dev/zig/build-release/lib/zig/std/zig.zig
New sane text for document file:///c%3A/dev/zig/build-release/lib/zig/std/zig.zig
INVALID: Id.TestDecl
New sane text for document file:///c%3A/dev/test2.zig
New sane text for document file:///c%3A/dev/test2.zig
New sane text for document file:///c%3A/dev/test2.zig
Import removed: file:///c%3A/dev/zig/build-release/lib/zig/std/std.zig
Freeing document: file:///c%3A/dev/zig/build-release/lib/zig/std/std.zig
Freeing document: file:///c%3A/dev/zig/build-release/lib/zig/std/zig.zig
```

**Comment by alexnask** [comment]
I think this is ready to merge.  
A couple of known issues:  
- Self parameters in function completions are not removed (this is general, not specific to this PR)  
- We show non-pub declarations from the imports  
- Completions like `const ArrayList = @import("std").ArrayList;` are not resolved to functions but variables.  
- Declarations like `const json = std.json;` do not yield completions when doing `json.`

**Comment by SuperAuguste** [comment]
This looks good! Merging now!

**Pull request merged**
