### PR TITLE
Parsing now always results in an AST

### PR DESCRIPTION
**Pull request by Vexu**
Update for https://github.com/ziglang/zig/pull/5336.

### CODE REVIEW

**Comment by alexnask** [comment]
Cool, this looks good, thanks for the style fixes as well.

**Comment by alexnask** [comment]
@Vexu It appears the parsing goes into a presumably infinite loop for some error cases (it consumes more and more memory until I have to kill the process).  

Here is a simple repro:  
```zig
const std = @import("std");

fn local_fn(comptime T: type, comptime V: type) type {
    return T;
}

pub fn main() void {
    // std.hash_map.AutoHashMap
    local_fn(comptime T: type, comptime V: type)
}

```

Launching zls for this document or calling `zig fmt` will block on the handle.tree call (aka `try std.zig.parse(allocator, handle.document.text);`)

**Comment by Vexu** [comment]
Ah nice, I also noticed the memory increasing sometimes but couldn't make a repro.

**Comment by SuperAuguste** [comment]
It seems that the infinite loop issue has been fixed in ziglang/zig#5336. I'll test this pull request out now!

**Comment by SuperAuguste** [comment]
Just tested this, it leaks over 1 gigabyte after a few seconds, as opposed to the normal `0.6 mbs` of memory on the current `zls` master. @alexnask believes this is an issue with your PR, #5336, as `zig fmt` has the same memory leak behavior.

**Comment by SuperAuguste** [comment]
The leak seems to be an edge case. Looking into it a little more.

**Comment by SuperAuguste** [comment]
I cannot recreate the memleak. I'll merge this and take it care of it when it (rarely) reappears later on!

**Pull request merged**
