### PR TITLE
support argument placeholder

### LINKED ISSUE #685: Feature flag request: Separate argument injection from snippets
Would it be possible to separate argument injection into its own config independent of `enable_snippets`?

With `enable_snippets` enabled, accepting a function completion also injects the function's args and types,

e.g.

```zig
exe.addCS
```
is completed to

```zig
exe.addCSourceFile(file: []const u8, flags: []const []const u8)
```

instead of

```zig
exe.addCSourceFile()
```

I'm sure this is quite useful to some people and some code editors, but it seems like a separate functionality to be toggled independently (and to me it is quite annoying).

So basically change the code here to use different flag, and add docs for it & everything https://github.com/zigtools/zls/blob/8eeae0286559a5765adb55d82c4b2046786fcc58/src/Server.zig#L498

I can create a PR if you are ok with the change.

### PR DESCRIPTION
**Pull request by jiacai2050**
Close #685

### CODE REVIEW

**Comment by leecannon** [comment]
You need to add the option to `src/config_gen/config.json` then run `zig build gen`.

Also the default should be true to match the current behaviour.

**Comment by jiacai2050** [comment]
PTAL

**Comment by leecannon** [comment]
This isn't working correctly.

Below is the result of completion of `std.debug.print`, the text is what is actually inserted into the editor:

| | `enable_argument_placeholders` true | `enable_argument_placeholders` false |
|-|-|-|
| `enable_snippets` true  | `std.debug.print(comptime fmt: []const u8, args: anytype)`| `std.debug.print(${})` |
| `enable_snippets` false | `std.debug.print(${1:comptime fmt: []const u8}, ${2:args: anytype})` | `std.debug.print(${})` |

Example:
image

This is what should be inserted into the editor:
| | `enable_argument_placeholders` true | `enable_argument_placeholders` false |
|-|-|-|
| `enable_snippets` true  | `std.debug.print(comptime fmt: []const u8, args: anytype)` | `std.debug.print()` |
| `enable_snippets` false | `std.debug.print` | `std.debug.print`|

So the only combination working as expected is when both are true.

**Comment by jiacai2050** [comment]
Ooops, I have make changes to make result right, but I have one question, 

when enable_snippets = true, enable_argument_placeholders = false, if we output `std.debug.print()`, cursor will be put after `)`

If we output `std.debug.print(${})`, cursor will be put after `(`, which is more reasonable to me.

**Comment by leecannon** [comment]
Correct with snippets but not argument placeholders, it should be `std.debug.print(^)` (`^` used to signify cursor location after accepting completion) but what was happening was `std.debug.print(${})^` with the `${}` actually inserted into the document and not handled specially by the editor.

I haven't check the behaviour of the latest commit, as I'm still at work and should not even being looking at this right now :),

**Comment by leecannon** [comment]
I've added a commit which ensures the placement of the cursor is correct when argument placeholders are disabled but snippets are enabled.

This PR is looking good to merge however it won't be merged until #1311 is to prevent more conflicts building up on that PR, don't worry though it should only be a couple of days.

**Review by leecannon — APPROVED** [review]

**Pull request merged**
