### PR TITLE
Update Zig master `@branchHint` and `builtin` type fields

### PR DESCRIPTION
**Pull request by mochalins**

### CODE REVIEW

**Comment by mochalins** [comment]
Minimum Zig version not available to CI yet, must re-run once available. Tests pass locally on Linux x86_64. Tests fail for x86_64 Windows through Wine, for what appear to be Wine-specific reasons (hundreds of `fixme` and `XXX not implemented yet` errors logged during test).

**Comment by xdBronch** [comment]
there are some more breaking changes on master, https://github.com/ziglang/zig/pull/21225 and possibly https://github.com/ziglang/zig/pull/21231 eventually (havent checked if this one affects zls). could maybe do them all here so there arent multiple prs trying to update?

**Comment by mlugg** [comment]
breaking changes are my passion

**Comment by mochalins** [comment]
> there are some more breaking changes on master, https://github.com/ziglang/zig/pull/21225 and possibly https://github.com/ziglang/zig/pull/21231 eventually (havent checked if this one affects zls). could maybe do them all here so there arent multiple prs trying to update?

Sure, will do!

**Comment by devraymondsh** [comment]
Still waiting for this fix to be merged.

**Comment by mochalins** [comment]
Updated with all tests passing on latest master (`0.14.0-dev.1392+37df6ba86`). Depends on https://github.com/zigtools/zig-lsp-codegen/pull/18, `build.zig.zon` must be updated after it is merged.

**Review by Techatrix — APPROVED** [review]
thank you

**Pull request merged**
