### PR TITLE
Report zls version using git describe

### PR DESCRIPTION
**Pull request by Techatrix**
Outputs something like `0.9.0-210-gda03c81`

### CODE REVIEW

**Comment by Techatrix** [comment]
"It works on my machine"
¯\\\_( ͡° ͜ʖ ͡°)_/¯

**Comment by SuperAuguste** [comment]
I love it but this CI failure means that this won't work on build artifacts/releases :(

Maybe we could add an environment variable bypass and set that environment variable to the latest commit somehow?

**Comment by Techatrix** [comment]
Adding `fetch-depth: 0` between line 18 & 19 to the checkout action should fix this. I've tried it out on my [fork](https://github.com/Techatrix/zls/actions/runs/2973995071).
https://github.com/zigtools/zls/blob/d72cac04ab0d048e0014294fd125a0a1db3b4845/.github/workflows/main.yml#L17-L19
I've also seen there are new versions `checkout@v3` and `upload-artifact@v3` available. I am not really experienced with CI so i hope this helps.

**Comment by SuperAuguste** [comment]
Oh awesome, feel free to adjust that in this PR! That way the CI will pass and this can be merged! :)

**Review by SuperAuguste — APPROVED** [review]
Sorry for the delay, LGTM! :)

**Pull request merged**
