### PR TITLE
Add Neovim/Vim8 option to config wizard

### PR DESCRIPTION
**Pull request by kubkon**
This commit adds minimal config option for Neovim/Vim8 editors
in the config wizard. It assumes use of CoC engine to facilitate
LSP.

### CODE REVIEW

**Comment by data-man** [comment]
Update README.md?

**Comment by kubkon** [comment]
> Update README.md?

Oh crap, of course, thanks for spotting that one! Fixed in e4e13ea.

**Comment by kubkon** [comment]
Forgot to update the ToC. Should be good to go now! Lemme know if something is still missing.

**Comment by SuperAuguste** [comment]
This looks good to me! Thanks for the contribution @kubkon!

**Pull request merged**
