### PR TITLE
Miscellaneous zig std api breaking fix

### PR DESCRIPTION
**Pull request by jimying**
Fix zig std api breaking list:
- zig std had removed meta.trait  
  https://github.com/ziglang/zig/commit/d5e21a4f1a2920ef7bbe3c54feab1a3b5119bf77 
  https://github.com/ziglang/zig/pull/18061
- std.fs: split Dir into IterableDir
 https://github.com/ziglang/zig/pull/12060
- rework std.atomic
 https://github.com/ziglang/zig/pull/18085

### CODE REVIEW

**Review by nektro — APPROVED** [review]

**Review by nullptrdevs — COMMENTED** [review]
Make sure to test that it builds with `-Doptimize=ReleaseSafe`

https://github.com/jimying/zls/blob/19fbc295569f50322df30f71243dd09c69f288f4/src/binned_allocator.zig#L136-L138

**Comment by nullptrdevs** [comment]
`/home/runner/.cache/zig/p/1220f9d9dd88b1352b1a2bde4a96f547a1591d66ad0a9d76854d0c2c7fa59eef2508/known-folders.zig:66:44: error: root struct of file 'os.windows' has no member named 'shell32'`

Any Windows users willing to do a PR?

**Comment by SuperAuguste** [comment]
https://github.com/ziglibs/known-folders/pull/42 :)

**Review by nullptrdevs — APPROVED** [review]
Tested

**Pull request merged**
