### PR TITLE
use realpathAlloc to make paths from zig env absolute

### LINKED ISSUE #1406: ZLS doesn't resolve relative paths fronm `zig env`
### Zig Version

0.12.0-dev.66+5e0107fbc

### Zig Language Server Version

ee9595132b1ac8d5c10e23e03a7059199cb63547

### Steps to Reproduce

1. Install GNU Emacs 28.2
2. Install the `eglot` package from MELPA.
3. Open a zig source file in a parent directory of the Zig library directory. `M-x eglot`.
4.  Enter:
```
const std = @import("std");
const Foo = std.Arr
```
5. With the cursor after the last `r`, press `C-M-i`.
6. Note the output of `zig env`:
```
$ [~/Downloads]> zig env
{
 "zig_exe": "/home/user/Downloads/zig/zig",
 "lib_dir": "zig/lib",
 "std_dir": "zig/lib/std",
 "global_cache_dir": "/home/user/.cache/zig",
 "version": "0.12.0-dev.66+5e0107fbc",
 "target": "x86_64-linux.6.4...6.4-gnu.2.19"
}
```

```
(:jsonrpc "2.0" :id "i_haz_configuration" :result
          [nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil])
[server-notification] Tue Aug 15 23:18:45 2023:
(:jsonrpc "2.0" :method "textDocument/publishDiagnostics" :params
          (:uri "file:///home/user/Downloads/kc-z1.zig" :diagnostics
                [(:range
                  (:start
                   (:line 113 :character 25)
                   :end
                   (:line 113 :character 35))
                  :severity 1 :code "expected_semi_after_stmt" :source "zls" :message "expected ';' after statement")]))
[stderr] warning: (server): config option 'zig_lib_path': expected absolute path but got 'zig/lib'
[server-notification] Tue Aug 15 23:18:45 2023:
(:jsonrpc "2.0" :method "window/showMessage" :params
          (:type 2 :message "config option 'zig_lib_path': expected absolute path but got 'zig/lib'"))
```

### Expected Behavior

The expected behavior is for ZLS to issue completions.

### Actual Behavior

No completions are given.

Log:
```
[client-request] (id:74) Tue Aug 15 23:32:33 2023:
(:jsonrpc "2.0" :id 74 :method "textDocument/completion" :params
          (:textDocument
           (:uri "file:///home/user/Downloads/kc-z1.zig")
           :position
           (:line 12 :character 19)
           :context
           (:triggerKind 1)))
[server-reply] (id:74) Tue Aug 15 23:32:33 2023:
(:jsonrpc "2.0" :id 74 :result nil)
```

### PR DESCRIPTION
**Pull request by notcancername**
closes #1406

### CODE REVIEW

**Review by SuperAuguste — APPROVED** [review]

**Comment by SuperAuguste** [comment]
Can you quickly make sure this still works with manually specified absolute paths? Otherwise we might need an absolute check before running realpath, no idea if it's required which is why I'm asking :)

**Comment by notcancername** [comment]
yep!
`$ [~/src/random] > zig env`
```json
{
 "zig_exe": "/home/user/Downloads/zig/zig",
 "lib_dir": "/home/user/Downloads/zig/lib",
 "std_dir": "/home/user/Downloads/zig/lib/std",
 "global_cache_dir": "/home/user/.cache/zig",
 "version": "0.12.0-dev.66+5e0107fbc",
 "target": "x86_64-linux.6.4...6.4-gnu.2.19"
}
```
image

**Comment by SuperAuguste** [comment]
Awesome - thank you so much!

**Comment by Techatrix** [comment]
the realpath function should be avoided, `std.fs.path.resolve` with the cwd is probably closed to what is needed.

**Pull request merged**
