### PR TITLE
clean up Nix flake using zon2nix

### LINKED ISSUE #1024: Builtin dependency system will break nix flake.
### Zig Version

0.11.0-dev.1782+b52be973d

### Zig Language Server Version

1a7b0a7a70e19070445db98be1393b6cef3b0052

### Steps to Reproduce

When #1017 gets accepted, it will break nix flakes as nix does not allow the build tool to download files during the build phase (or any other phase). To fix it, we can change the flake.nix file to:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    zig-overlay.url = "github:mitchellh/zig-overlay";
    zig-overlay.inputs.nixpkgs.follows = "nixpkgs";

    gitignore.url = "github:hercules-ci/gitignore.nix";
    gitignore.inputs.nixpkgs.follows = "nixpkgs";

    flake-utils.url = "github:numtide/flake-utils";

    known-folders.url = "https://github.com/ziglibs/known-folders/archive/53fe3b676f32e59d46f4fd201d7ab200e5f6cb98.tar.gz";
    known-folders.flake = false;

    tres.url = "https://github.com/ziglibs/tres/archive/d8b0c24a945da02fffdae731edd1903c6889e73c.tar.gz";
    tres.flake = false;

    diffz.url = "https://github.com/ziglibs/diffz/archive/efc91679b000a2d7f86fb40930f0a95a0d349bff.tar.gz";
    diffz.flake = false;
  };

  outputs = { self, nixpkgs, zig-overlay, gitignore, flake-utils, known-folders, tres, diffz }:
    let
      systems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      inherit (gitignore.lib) gitignoreSource;
    in
    flake-utils.lib.eachSystem systems (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        zig = zig-overlay.packages.${system}.master;
      in
      rec {
        packages.default = packages.zls;
        packages.zls = pkgs.stdenvNoCC.mkDerivation {
          name = "zls";
          version = "master";
          src = gitignoreSource ./.;
          nativeBuildInputs = [ zig ];
          dontConfigure = true;
          dontInstall = true;
          buildPhase = ''
            mkdir -p $out
            mkdir -p .cache/{p,z,tmp}
            cp -r ${known-folders} .cache/p/12203e18503cd0fa097a4404b0c4f8535a68536886b536ae51c786455238ba5f183b
            cp -r ${tres} .cache/p/12209914477ef8c4ef99accb293c4a7ec90acdd9e77d3f60f5e056449cbfad3a7fd8
            cp -r ${diffz} .cache/p/122019f94ec81a7cf6e9810983603dbacfc65ed30aea8f277f05ba0ce7c1511fff3d
            zig build install --cache-dir $(pwd)/zig-cache --global-cache-dir $(pwd)/.cache -Dcpu=baseline -Doptimize=ReleaseSafe -Ddata_version=master --prefix $out
          '';
        };
      }
    );
}
```

However, this hardcodes the hashes and urls, which are already present in the zon file. It would be nice to somehow parse the file and get the info from there, but I have no idea of how to do it. So, it solves the problem, but not in an ideal way. I'm not opening a pull-request because #1017 wasn't accepted yet and I not super happy with the hardcoding solution.

### Expected Behavior

N/A

### Actual Behavior

N/A

### PR DESCRIPTION
**Pull request by figsoda**
now updating the nix flake just needs one command (`zon2nix > deps.nix`) and we are no longer relying on the magic that stopped comments from working

closes #1024 

also reverts #1265 and updated the comment, as comments are now allowed

### CODE REVIEW

**Comment by figsoda** [comment]
fixed merge conflicts

**Comment by figsoda** [comment]
cc @Techatrix @leecannon

**Comment by SuperAuguste** [comment]
Sorry for the late reply! We don't actually have any maintainers who are Nix users as far as I'm aware so this fell through the cracks.

@acristoffers sorry to bug you but you really seem to know your nix - at a glimpse this looks correct, just want to make sure I'm not missing anything; could you leave a review if you have time? :)

**Comment by acristoffers** [comment]
@figsoda did what I wanted to do since the beginning but never got to it because I didn't want to manage the dependency tree myself (which it seem zig is not going to have, it's going to be flat). So thanks @figsoda for the project and for cleaning up the mess of ((((functions)))) I had to use to do it in nix with less manual interference :)

**Comment by acristoffers** [comment]
And no problem pinging me @SuperAuguste :)

**Comment by figsoda** [comment]
resolved merge conflicts

**Comment by figsoda** [comment]
> Sorry for the late reply! We don't actually have any maintainers who are Nix users as far as I'm aware so this fell through the cracks.

No worries

**Comment by Techatrix** [comment]
> We don't actually have any maintainers who are Nix users as far as I'm aware

Actually, I do use NixOS as my operating system but I do not have the necessary expertise to review this PR. 
But I do think that ideally there should not be any need manually manage zig dependencies with `zon2nix`. If there are helpers like `rustPlatform.buildRustPackage`, then where is something like `buildZigPackage`?

**Comment by figsoda** [comment]
> Actually, I do use NixOS as my operating system but I do not have the necessary expertise to review this PR. But I do think that ideally there should not be any need manually manage zig dependencies with `zon2nix`. If there are helpers like `rustPlatform.buildRustPackage`, then where is something like `buildZigPackage`?

Unfortunately `build.zig.zon` uses a different hash format compared to the ones nix support, so to use these dependencies with nix, one has to either keep track of one FOD hash (like `cargoHash` / `fetchCargoTarball`) that needs to be manually updated, or the approach zon2nix takes, since the `importCargoLock` equivalent in zig is not possible due to the differences in hashing algorithms.

**Review by acristoffers — APPROVED** [review]

**Review by acristoffers — APPROVED** [review]

**Comment by acristoffers** [comment]
At least 1 approving review is required by reviewers **with write access**.

Well, that's not me 🙃

**Review by SuperAuguste — APPROVED** [review]

**Comment by figsoda** [comment]
resolved merge conflicts

**Pull request merged**
