### PR TITLE
Remove desitination type param from cast builtins (update to compile using zig master)

### PR DESCRIPTION
**Pull request by antlilja**
This PR updates zls to be compatible with zig master after the change which removes the type parameter from cast builtins.

It depends on PRs in dependencies:
- [x] https://github.com/ziglibs/tres/pull/15
- [x] https://github.com/ziglibs/diffz/pull/15
- [x] https://github.com/ziglibs/known-folders/pull/36
- [x] https://github.com/zigtools/sus/pull/16

### CODE REVIEW

**Comment by leecannon** [comment]
@antlilja You will also need to run `zig build gen -- --generate-version-data master` to update the completions/documentation of builtins.

**Comment by Techatrix** [comment]
all affected builtins should also be removed from this section:
https://github.com/zigtools/zls/blob/38a12a51d76fff9bed66461ecb27ef8b93cca350/src/analysis.zig#L986-L1004

**Comment by antlilja** [comment]
I've now submitted PRs to sus and zig-lsp which sus depends on. zig-lsp also depends on tres.
- [ ] https://github.com/zigtools/sus/pull/16
- [ ] https://github.com/ziglibs/zig-lsp/pull/4

**Comment by SuperAuguste** [comment]
All dependent PRs merged; anything left here? :)

**Comment by leecannon** [comment]
Good job with this @antlilja 👍

**Comment by SuperAuguste** [comment]
^ Thank you so much for taking care of this @antlilja!! :)

**Comment by antlilja** [comment]
> ^ Thank you so much for taking care of this @antlilja!! :)

No problem!

**Pull request merged**
