### PR TITLE
revive C import support

### LINKED ISSUE #1080: cimport crashes due to Zig not respecting `--enable-cache`
### Zig Version

0.11.0-dev.2191+30427ff79

### Zig Language Server Version

0.11.0-dev.332+a929576

### Steps to Reproduce

start typing inside `main`:
```zig
const std = @import("std");

pub fn main() !void {
    
}

usingnamespace @cImport({});
```

### Expected Behavior

no crash

### Actual Behavior

```
debug: (store ): Translated cImport into file://pub const __builtin_bswap16 %3D %40import%28"std"%29.zig.c_builtins.__builtin_bswap16%3B
thread 46379 panic: reached unreachable code
/home/lee/zig/0.11.0-dev.2191+30427ff79/files/lib/std/debug.zig:281:14: 0x34a52c in assert (zls)
    if (!ok) unreachable; // assertion failure
             ^
/home/lee/zig/0.11.0-dev.2191+30427ff79/files/lib/std/fs.zig:2729:27: 0x354eaa in openFileAbsolute (zls)
    assert(path.isAbsolute(absolute_path));
                          ^
/home/lee/src/zls/src/DocumentStore.zig:796:39: 0x5e88f1 in createDocumentFromURI (zls)
    var file = std.fs.openFileAbsolute(file_path, .{}) catch return null;
                                      ^
/home/lee/src/zls/src/DocumentStore.zig:135:47: 0x5e84ff in getOrLoadHandleInternal (zls)
    handle.* = (try self.createDocumentFromURI(uri, false)) orelse return error.Unknown; // error name doesn't matter
                                              ^
/home/lee/src/zls/src/DocumentStore.zig:126:40: 0x54e400 in getOrLoadHandle (zls)
    return self.getOrLoadHandleInternal(uri) catch null;
                                       ^
/home/lee/src/zls/src/analysis.zig:1057:66: 0x4c6988 in resolveTypeOfNodeUncached (zls)
                const new_handle = analyser.store.getOrLoadHandle(cimport_uri) orelse return null;
                                                                 ^
/home/lee/src/zls/src/analysis.zig:675:63: 0x4376c6 in resolveTypeOfNodeInternal (zls)
    const type_handle = try analyser.resolveTypeOfNodeUncached(node_handle);
                                                              ^
/home/lee/src/zls/src/analysis.zig:2149:63: 0x5cc3a7 in iterateSymbolsGlobalInternal__anon_56308 (zls)
                .{ .node = handle.tree.nodes.items(.data)[use].lhs, .handle = handle },
                                                              ^
/home/lee/src/zls/src/analysis.zig:2174:53: 0x53b949 in iterateSymbolsGlobal__anon_48789 (zls)
    return try analyser.iterateSymbolsGlobalInternal(handle, source_index, callback, context);
                                                    ^
/home/lee/src/zls/src/features/completions.zig:495:45: 0x4c0bfa in completeGlobal (zls)
    try server.analyser.iterateSymbolsGlobal(handle, pos_index, declToCompletion, context);
                                            ^
/home/lee/src/zls/src/features/completions.zig:836:50: 0x435ea5 in completionAtIndex (zls)
        .var_access, .empty => try completeGlobal(server, source_index, handle),
                                                 ^
/home/lee/src/zls/src/Server.zig:1098:45: 0x3f4792 in completionHandler (zls)
    return try completions.completionAtIndex(server, source_index, handle);
                                            ^
/home/lee/src/zls/src/Server.zig:1756:35: 0x3af591 in processMessage (zls)
                break :blk handler(server, params) catch |err| {
                                  ^
/home/lee/src/zls/src/Server.zig:1613:26: 0x35bf7a in processJsonRpc (zls)
    server.processMessage(message) catch |err| switch (message) {
                         ^
/home/lee/src/zls/src/main.zig:80:30: 0x35b73b in loop (zls)
        server.processJsonRpc(json_message);
                             ^
/home/lee/src/zls/src/main.zig:395:13: 0x35cb08 in main (zls)
    try loop(server, record_file, replay_file);
            ^
/home/lee/zig/0.11.0-dev.2191+30427ff79/files/lib/std/start.zig:617:37: 0x344efe in posixCallMainAndExit (zls)
            const result = root.main() catch |err| {
                                    ^
/home/lee/zig/0.11.0-dev.2191+30427ff79/files/lib/std/start.zig:376:5: 0x344961 in _start (zls)
    @call(.never_inline, posixCallMainAndExit, .{});
    ^
```

### PR DESCRIPTION
**Pull request by Techatrix**
Its time to bring back C import support. fixes #1080
Please feel free to try this out and report any issues.

error reporting currently doesn't work because of an issue on the zig side (I suspect)

### CODE REVIEW

**Comment by silversquirl** [comment]
Doesn't seem to be working for me - translate-c errors out with `UnexpectedEOF`

Full zls log:
```
info : (config): Using zig executable '/home/silver/.local/bin/zig'
info : (config): Using zig lib path '/home/silver/.opt/zig/lib'
info : (config): Using build runner global cache path '/home/silver/.cache/zig'
info : (config): Detected runtime zig version: '0.11.0-dev.2614+7b908e173'
info : (server): client is 'kak-lsp-14.2.0'
info : (server): zls initializing
info : (server): Server.ClientCapabilities{ .supports_snippets = false, .supports_apply_edits = true, .supports_will_save = false, .supports_will_save_wait_until = false, .supports_publish_diagnostics = true, .supports_code_action_fixall = false, .hover_supports_md = true, .completion_doc_supports_md = true, .label_details_support = false, .supports_configuration = true, .supports_workspace_did_change_configuration_dynamic_registration = false }
info : (server): Using offset encoding: utf-8
warning: (store ): Document already open: file:///home/silver/code/pipit/src/CodeGen.zig
info : (server): Setting configuration...
info : (config): Using zig executable '/home/silver/.local/bin/zig'
info : (config): Using zig lib path '/home/silver/.opt/zig/lib'
info : (config): Using build runner global cache path '/home/silver/.cache/zig'
info : (config): Detected runtime zig version: '0.11.0-dev.2614+7b908e173'
info : (server): Setting configuration...
info : (config): Using zig executable '/home/silver/.local/bin/zig'
info : (config): Using zig lib path '/home/silver/.opt/zig/lib'
info : (config): Using build runner global cache path '/home/silver/.cache/zig'
info : (config): Detected runtime zig version: '0.11.0-dev.2614+7b908e173'
info : (server): Setting configuration...
info : (config): Using zig executable '/home/silver/.local/bin/zig'
info : (config): Using zig lib path '/home/silver/.opt/zig/lib'
info : (config): Using build runner global cache path '/home/silver/.cache/zig'
info : (config): Detected runtime zig version: '0.11.0-dev.2614+7b908e173'
info : (server): Setting configuration...
info : (config): Using zig executable '/home/silver/.local/bin/zig'
info : (config): Using zig lib path '/home/silver/.opt/zig/lib'
info : (config): Using build runner global cache path '/home/silver/.cache/zig'
info : (config): Detected runtime zig version: '0.11.0-dev.2614+7b908e173'
error: (translate_c): failed zig translate-c command:
/home/silver/.local/bin/zig translate-c --zig-lib-dir /home/silver/.opt/zig/lib --cache-dir /home/silver/.cache/zls -lc --listen=- -I /usr/local/include -I /usr/include/x86_64-linux-gnu -I /usr/include /home/silver/.cache/zls/cimport.h
error:error.UnexpectedEOF

error: (store ): failed to translate cimport: error.UnexpectedEOF
```

**Comment by Techatrix** [comment]
I should have read that log more carefully, my bad. I thought I just fixed that error.

**Comment by silversquirl** [comment]
No error any more, but still no completions. It works when I `@cImport(@cInclude("stdlib.h"))` outside of a project though - seems like it's just not working with headers from packages?

**Comment by Techatrix** [comment]
resolving include paths from build.zig may not work correctly anymore. I will check later if something regressed.

**Comment by neurocyte** [comment]
This works well for me when rebased to zls master.

**Comment by Ultra-Code** [comment]
@Techatrix thanks for your work on this feature. Completions currently work but hover for identifier information doesn't work.

In `neovim 0.9.0` I get 
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1682: 'width' key must be a positive Integer
stack traceback:
	[C]: in function 'nvim_open_win'
	/usr/share/nvim/runtime/lua/vim/lsp/util.lua:1682: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:1394: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
on hover

**Comment by Techatrix** [comment]
Can you provide me with an example and steps you took to get this error? Information on your neovim setup would also be appreciated because I don't have much experience dealing with neovim.

**Review by leecannon — APPROVED** [review]

**Comment by leecannon** [comment]
Works on all my projects that use cimport.

Including a non-existant file results in an error in the log but zls keeps going :+1: 

<details>
  <summary>Error</summary>
  
```
debug: (server): Took 1ms to process method textDocument/didChange
error: (translate_c): failed zig translate-c command:
/home/lee/bin/zig translate-c --zig-lib-dir /home/lee/zig/0.11.0-dev.3322+82632aff2/files/lib --cache-dir /home/lee/.cache/zls -lc --listen=- -I /usr/local/include -I /usr/include/x86_64-linux-gnu -I /usr/include -I /home/lee/src/zig-libgit2/../libgit2/include /home/lee/.cache/zls/cimport.h
error:error.Timeout

error: (store ): failed to translate cimport: error.Timeout
debug: (server): Took 29ms to process method textDocument/completion
```
</details>

**Comment by Techatrix** [comment]
> Completions currently work but hover for identifier information doesn't work.

@Ultra-Code #1232 should have fixed your hover issue. (nice nvim config btw)

**Comment by Ultra-Code** [comment]
@Techatrix thanks for the fix, Indeed the hover works now 😄 .

**Pull request merged**
