### PR TITLE
fix openDir with iterate

### PR DESCRIPTION
**Pull request by jiacai2050**
See https://github.com/zigtools/zls/issues/468#issuecomment-1186441812

### CODE REVIEW

**Comment by SuperAuguste** [comment]
Closing in favor of #544.

**Comment by jiacai2050** [comment]
Hi @SuperAuguste, thanks for point out.

BTW, how often will https://ziglang.org/download/ update to latest master version?

I think it's important for user to build zls with those pre-built version.

**Comment by SuperAuguste** [comment]
Absolutely! I'm not an authority on this topic but I believe that that page updates once a day!

**Comment by Luukdegram** [comment]
It updates when the CI completes successfully on the master branch. So technically this could be multiple times a day.

**Pull request closed without merging**
