### PR TITLE
Use @silversquirl's binned allocator

### PR DESCRIPTION
**Pull request by SuperAuguste**

### CODE REVIEW

**Comment by Techatrix** [comment]
I would suggest to use the GPA in debug builds by default.

**Comment by Jarred-Sumner** [comment]
using `c_allocator` fixes https://github.com/zigtools/zls/issues/1128

haven't tried with this

**Comment by SuperAuguste** [comment]
Took your suggestion and applied it, sorry this took so long!

**Comment by Jarred-Sumner** [comment]
can you merge this

**Comment by Jarred-Sumner** [comment]
thank you

**Pull request merged**
