### PR TITLE
provide build_runner command on failure

### LINKED ISSUE #566: Proposal: dump stderr when loading packages from build.zig fails.
Ever since zls has had a way to load packages from a build.zig, there have always been weird, silent bugs that have prevented some (or all in some cases) users from having *any* package completions. Most of the silence is due to the fact that when zls exec's zig to run the build runner, it only returns an error indicating failure.

It would be helpful if zls *also* kept track of stderr and would log it before erroring out to the caller.

### PR DESCRIPTION
**Pull request by leecannon**
A few times i've had to read the code in `loadPackages` to figure out the correct command to execute the build_runner to debug an issue.
Closes #566

### CODE REVIEW

**Comment by truemedian** [comment]
It would also be helpful if zls also logged stderr when the command fails like #566

**Comment by leecannon** [comment]
@truemedian: i've added stderr output

Closes #566

**Comment by truemedian** [comment]
ah sorry if I wasn't clear, I meant logging zig_run_result's stderr

**Comment by leecannon** [comment]
fixed, that does make more sense :)

**Comment by SuperAuguste** [comment]
LGTM, thanks again Lee!

**Pull request merged**
