### PR TITLE
Allocator.resize() does not adjust size of string allocated for URI to file path conversion

### PR DESCRIPTION
**Pull request by josephst**
Related to problem #804 - escape sequences are removed from the string as it is being built which results in the final string never filling up the memory that was allocated for it. 

This results in a URI such as `file:///c%3A/main%2B.zig` being given 4 more bytes of memory than necessary (and these bytes are left undefined/ uninitialized~). 

URI.parse() correctly calculates the size of the final string (based on inspecting `i` in URI.parse() with a debugger) but the final call to `allocator.resize(allocator.resize(uri, i)) does not actually affect the size of the array. 

This pull request currently includes tests that fail as a result of this bug. Still working on fixing the underlying bug but wanted to include some tests in case anyone else out there can fix the problem sooner!

### CODE REVIEW

**Comment by SuperAuguste** [comment]
You accidentally included your VSCode config in the mix by the way :P

**Comment by SuperAuguste** [comment]
Wow `realloc` is exactly what we need - totally missed it, nice find! Could you please quickly rebase this (merge conflicts currently present in `uri.zig`) - thanks! :)

**Comment by josephst** [comment]
Ah - so I did 😅 luckily just my testing config! 
Just pushed another commit with a call to `allocator.resize()` which appears (in brief testing) to properly reduce the length of the array!

**Comment by josephst** [comment]
Anyways, you seem to be catching my commits faster than I can type them up! Going to leave the rest to you to fix the merge conflict - thanks for getting it fixed up!

**Comment by SuperAuguste** [comment]
Testing this locally, `realloc` seems to be just as unreliable - it seems to return uninitialized memory, causing test failures.

**Comment by josephst** [comment]
Also, from looking at the CI runners, the tests for windows-specific formatting (specifically, `file:///c/...` instead of `file://src/...` may be causing problems - these can just be commented out or something. To be honest, I was picking up Zig for doing Advent of Code exercises so I'm a bit over my head! Not sure if there's an easy way in Zig to have certain tests only run on windows CI runners

**Comment by SuperAuguste** [comment]
No worries I'll handle it :)

**Comment by josephst** [comment]
Investigated this for a while this morning - I think the best approach right now is just to isolate the platform-specific code to that particular test runner (test Windows-specific formatting on Windows test runners, etc)

From looking at how Python does it, the [as_uri](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_uri) method produces Unix or Windows style URIs but pathlib lacks any good way to convert from URI to file path. Meanwhile [urllib](https://docs.python.org/3/library/urllib.parse.html#module-urllib.parse) has various methods for converting from a `file:///` URI to a local file path although it also doesn't seem particularly robust; converting a file path => URI => back to file path results in a leading slash being appended to the path. [There's ongoing discussion about it](https://discuss.python.org/t/file-uris-in-python/15600); clearly no great way to handle this cross-platform

```python
import pathlib
from urllib.parse import urlparse
urlparse(pathlib.PureWindowsPath("C:\\foo.txt").as_uri()) # ParseResult(scheme='file', netloc='', path='/C:/foo.txt', params='', query='', fragment='')
```

Anyways, isolating the tests to each platform so that Windows-specific URI stuff only runs on Windows test platforms and Unix-specific URI stuff only runs on Unix-like platforms seems to fix the URI parsing/ encoding problems. 

Additionally, latest commit also changes some of the `uri - pathRelative` test. `file://project/zig` refers to a file `zig` on host `project` whereas `file:///project/zig` refers to a file `zig` on localhost under the directory `/project`. I think testing the latter is better here.

**Comment by SuperAuguste** [comment]
Sounds good to me!

**Comment by SuperAuguste** [comment]
ayo it passed, thank you so much!

**Review by SuperAuguste — APPROVED** [review]

**Pull request merged**
