### PR TITLE
update for latest zig master branch zig-0.10.0-dev.2017+a0a2ce92c

### PR DESCRIPTION
**Pull request by neel-bp**
std.childprocess.init no longer returns an error union type
std.childprocess no longer has deinit member function.

### CODE REVIEW

**Comment by damag** [comment]
Hi, it seems that it no longer allocates a struct on the heap but returns it directly, so there is no need to deinit/destroy since &process would be an address on the stack.
You can see for examples of how the usage was updated in Zig itself: https://github.com/ziglang/zig/commit/a0a2ce92ca129d28e22c63f7bace1672c43776b5

**Comment by neel-bp** [comment]
okay i removed the defer, 
thank you for your patience i am pretty new to zig, and when i tried compiling zls i was having compilation errors, so i tried to fix it, and was able to do it, and decided to fork it and make PR, 
don't feel bad if you people think this pr is not up to standards.

**Comment by damag** [comment]
No worries, I'm not a maintainer, just another user that ran into the same issue as you, but removing the `try` and `deinit` line should do it. ;)

**Comment by damag** [comment]
Just noticed that the `try` in tests/sessions.zig line 111 is also causing the CI checks to fail.

**Comment by jacmoe** [comment]
Thanks, guys! The changes in those two files allowed me to (finally!) get latest Zig and latest Zls to get along :smile:

**Comment by neel-bp** [comment]
updated startZls test, thanks @damag

**Review by damag — COMMENTED** [review]
Just a few more things for `zig build test` to run successfully:

- The return type of `startZls()` should be changed to `!std.ChildProcess` since process is no longer a pointer.
- Likewise, `process` in the Server struct should be a simple `std.ChildProcess`
- And finally `self.process.deinit();` should be removed in the `Server.shutdown()` function

**Comment by truemedian** [comment]
`file://./tests/test.zig` is a valid URI, if it doesn't work it needs to be fixed too.
`file:///./tests/test.zig` is just `file:///tests/test.zig` which is an absolute path, not relative like the test (probably) intends

**Comment by guidorice** [comment]
In #291 this PR is mentioned as being the best candidate to zls working again. What else needs to be fixed here? File uris changed in zig or something? This branch seems to work to me , and `zig build test` succeeds (x86_64-macos). 

cc @damag @leecannon @neel-bp

**Comment by damag** [comment]
It works for me as well, although I agree with @truemedian, I don't know what the file uri change is about.

**Comment by SuperAuguste** [comment]
This PR looks good, I agree that the tests failing is unusual... Could you please rebase this (just merged suirad's build fix); thanks!

**Pull request closed without merging**
